# Generated by Django 2.2 on 2020-11-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201124_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={},
        ),
    ]
