# Generated by Django 2.2 on 2020-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания'),
        ),
    ]
