# Generated by Django 2.2 on 2020-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20201126_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
