# Generated by Django 2.2 on 2020-11-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20201128_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_dislike',
            new_name='users_dislike',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
