# Generated by Django 2.2 on 2020-11-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20201128_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='users_dislike',
        ),
    ]
